### ISSUE TITLE
Pairing fails with iPhone 5 on 8.4.1 and iPhone 7 on iOS 10

### ISSUE THREAD

**Issue by TheRealClarity** [doronz88/pymobiledevice3#44]
**Test environment**
- Big Sur 11.3.1
- iPhone 5 8.4.1 / iPhone 7 10.1.1

**Describe the bug**
Any sort of command fails due to a pairing error. Device is paired with the computer, and fully visible in Finder. ```idevicepair pair``` shows the device as paired. Other devices work fine, on iOS 14.

**To Reproduce**
1. Run any command, for example ```pymobiledevice3 afc shell```
2. Observe the error output.

**Logs**
```
2021-05-22 07:20:37 Mac-Pro-de-user.local root[6458] WARNING No iTunes pairing record found for device 83a380e899daa02d975c2fddb23e5c23918ed6e0
2021-05-22 07:20:37 Mac-Pro-de-user.local pymobiledevice3.lockdown[6458] WARNING Looking for pymobiledevice3 pairing record
2021-05-22 07:20:37 Mac-Pro-de-user.local pymobiledevice3.lockdown[6458] ERROR No pymobiledevice3 pairing record found for device 83a380e899daa02d975c2fddb23e5c23918ed6e0
2021-05-22 07:20:37 Mac-Pro-de-user.local pymobiledevice3.lockdown[6458] INFO Creating host key & certificate
......................................+++++
.........+++++
Traceback (most recent call last):
  File "/Users/user/Library/Python/3.8/bin/pymobiledevice3", line 8, in <module>
    sys.exit(cli())
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/pymobiledevice3/__main__.py", line 35, in cli
    cli_commands()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1666, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 2326, in process_value
    value = self.callback(ctx, self, value)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 26, in udid
    return LockdownClient(udid=value)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/pymobiledevice3/lockdown.py", line 107, in __init__
    self.pair()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/pymobiledevice3/lockdown.py", line 226, in pair
    cert_pem, private_key_pem, device_certificate = ca_do_everything(self.device_public_key)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/pymobiledevice3/ca.py", line 120, in ca_do_everything
    rsa2 = load_pub_key_bio(BIO.MemoryBuffer(
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/M2Crypto/RSA.py", line 444, in load_pub_key_bio
    rsa_error()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/M2Crypto/RSA.py", line 333, in rsa_error
    raise RSAError(Err.get_error_message())
M2Crypto.RSA.RSAError: unknown signature algorithm
```

**Comment by doronz88** [comment]
This seems to be a bug recognizing you have a specific iOS 14 version. What exact version are you using?

**Comment by doronz88** [comment]
I've merged an improvement to the version comparison. Please notify if this fixed the problem. If not, what specific iOS version are you using?

**Comment by TheRealClarity** [comment]
I'm using the latest version from this repository. I'm using 8.4.1 on an iPhone 5 and 10.1.1 on an iPhone 7. An iPad Pro on 14.3 is able to pair and use pymobiledevice3 successfully. The new version didn't solve the issue.

**Comment by doronz88** [comment]
Fixed.
